// Testa somente navegação; não publica pedidos nem altera dados reais.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../dist');
const server=http.createServer((req,res)=>{const file=path.join(root,new URL(req.url,'http://local').pathname);fs.readFile(file,(err,data)=>{if(err){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.webp')?'image/webp':'text/html');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.QF_CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox','--no-zygote','--single-process','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{const context=await browser.newContext({serviceWorkers:'block'});for(const width of [320,390,430,1440]){const page=await context.newPage();await page.setViewportSize({width,height:950});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());
await page.goto('http://127.0.0.1:'+server.address().port+'/index.html?demo=1');await page.waitForFunction(()=>window.navigate&&window.Screens);await page.locator('.qf-home-prof').waitFor();
const initial=await page.locator('.qf-landing-topbar').textContent();
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'largura '+width);
const boxes=await page.locator('.qf-landing-topbar > *').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return {left:r.left,right:r.right}}));for(let i=1;i<boxes.length;i++)assert.ok(boxes[i-1].right<=boxes[i].left+1,'topo sobreposto '+width);
for(const route of ['/auth/profissional/login','/anuncie']){await page.locator('.qf-home-prof summary').click();await page.locator('.qf-home-prof-menu [data-nav="'+route+'"]').click();await page.waitForFunction(r=>location.hash==='#'+r,route);await page.locator('[data-nav="/"]').first().click();await page.locator('.qf-home-prof').waitFor();assert.equal(await page.locator('.qf-landing-topbar').textContent(),initial);}
await page.locator('.qf-landing-login').click();await page.locator('#qf-login-cliente').click();await page.locator('#login-form').waitFor();await page.locator('[data-nav="/"]').first().click();
await page.locator('.qf-calc-entry').click();await page.waitForFunction(()=>location.hash==='#/calculadora');await page.goBack();await page.locator('.qf-home-prof').waitFor();
await page.locator('[data-landing-service-search]').fill('pintura');await page.locator('[data-landing-location]').fill('Santo André / SP');await page.locator('[data-landing-neighborhood]').fill('Vila Pires');await page.locator('[data-landing-service-form] [type="submit"]').click();await page.locator('#cadastro-cliente-form').waitFor();assert.equal(await page.locator('[name="cidade"]').inputValue(),'Santo André');assert.equal(await page.locator('[name="uf"]').inputValue(),'SP');assert.equal(await page.locator('[name="bairro"]').inputValue(),'Vila Pires');await page.locator('[data-nav="/"]').first().click();
// CEP e GPS: respostas controladas verificam integração sem usar a localização do usuário.
await page.evaluate(()=>{QFGeo.lookupCep=async()=>({cidade:'Campinas',uf:'SP'});QFGeo.currentPosition=async()=>({latitude:-23,longitude:-46});QFGeo.reverseGeocode=async()=>({cidade:'São Paulo',uf:'SP'});});
await page.locator('[data-home-gps]').click();await page.waitForFunction(()=>document.querySelector('[data-landing-location]').value==='São Paulo / SP');await page.locator('[data-landing-location]').fill('13000-000');await page.locator('[data-landing-service-search]').fill('serviço personalizado');await page.locator('[data-landing-neighborhood]').fill('Vila Pires');await page.locator('[data-landing-service-form] [type="submit"]').click();await page.locator('#cadastro-cliente-form').waitFor();assert.equal(await page.locator('[name="cidade"]').inputValue(),'Campinas');assert.equal(await page.locator('[name="servico"]').inputValue(),'serviço personalizado');await page.locator('[data-nav="/"]').first().click();
await page.reload();await page.locator('.qf-home-prof').waitFor();assert.equal(await page.locator('.qf-landing-topbar').textContent(),initial);
assert.equal(await page.locator('[data-landing-service-form] [type="submit"]').count(),1);assert.equal(await page.locator('.qf-big-cta').count(),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);
if(width===390||width===1440)await page.screenshot({path:'/tmp/quemfaz-home-'+width+'.png',fullPage:true});
await page.close();console.log('PASS '+width+'px: topo, profissional, empresa, entrar/voltar, histórico, calculadora, serviço, cidade, CEP, GPS e recarregamento; sem erros JS.');}
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
