const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'dist/index.html'),'utf8');
const sw=fs.readFileSync(path.join(root,'dist/sw.js'),'utf8');
const names=[...html.matchAll(/<script defer src="([^"]+)"/g)].map(x=>x[1]);
assert.ok(names.indexOf('vendor/supabase-2.117.2.js')<names.indexOf('app-main-11.34.1.js'));
assert.ok(names.indexOf('app-main-11.34.1.js')<names.indexOf('qf-recrutamento.js?v=11.33.1'));
assert.ok(names.indexOf('qf-recrutamento.js?v=11.33.1')<names.indexOf('app-shell-11.34.1.js'));
for(const name of names)assert.ok(fs.existsSync(path.join(root,'dist',name.split('?')[0])),name);
assert.ok(sw.includes('./app-main-11.34.1.js')&&sw.includes('./app-shell-11.34.1.js'));
assert.ok(html.includes('Precisou? Até <em>3 profissionais</em>'));
assert.ok(!fs.existsSync(path.join(root,'dist/node_modules')));
assert.ok(Buffer.byteLength(html)<200000);
const early=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].find(m=>m[1].includes('QFEarly'))[1];
const events={},field={value:'Preciso montar guarda-roupa',dispatchEvent(){}},form={tagName:'FORM',matches:()=>true,querySelector:()=>({}),requestSubmit(){this.sent=(this.sent||0)+1;}};
const document={querySelector:s=>s==='[data-landing-service-search]'?field:form,addEventListener:(key,fn)=>events[key]=fn};
const window={};vm.runInNewContext(early,{window,document,location:{hash:'#/'},Event:class{}});
let prevented=0;events.submit({target:form,preventDefault(){prevented++;}});
assert.equal(prevented,1);
field.value='';window.QFEarly.restore({querySelector:()=>field});assert.equal(field.value,'Preciso montar guarda-roupa');
window.QFEarly.finish();assert.equal(form.sent,1);
field.value='Novo serviço';window.QFEarly.capture();field.value='';window.QFEarly.restore({querySelector:()=>field});assert.equal(field.value,'');
console.log('publicacao-leve: ordem de scripts, cache offline, conteúdo inicial e preservação de pedido antes do carregamento: ok');
