const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'dist/index.html'),'utf8');
const sw=fs.readFileSync(path.join(root,'dist/sw.js'),'utf8');
const version=/const SW_VERSION = '([^']+)'/.exec(sw)[1];
const mainName=html.match(/app-main-[^"]+\.js/)[0],shellName=html.match(/app-shell-[^"]+\.js/)[0];
const names=[...html.matchAll(/<script defer src="([^"]+)"/g)].map(x=>x[1]);
assert.ok(names.indexOf('vendor/supabase-2.117.2.js')<names.indexOf(mainName));
assert.ok(names.indexOf(mainName)<names.indexOf('qf-recrutamento.js?v=11.33.1'));
assert.ok(names.indexOf('qf-recrutamento.js?v=11.33.1')<names.indexOf(shellName));
for(const name of names)assert.ok(fs.existsSync(path.join(root,'dist',name.split('?')[0])),name);
assert.ok(sw.includes('./'+mainName)&&sw.includes('./'+shellName));
assert.ok(html.includes('Conte o que precisa e veja <em>quem chama você.</em>'));
assert.ok(!fs.existsSync(path.join(root,'dist/node_modules')));
assert.ok(Buffer.byteLength(html)<210000,'HTML inicial deve ficar abaixo de 210 KB');
const early=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].find(m=>m[1].includes('QFEarly'))[1];
const events={},field={value:'Preciso montar guarda-roupa',dispatchEvent(){}},form={tagName:'FORM',matches:()=>true,querySelector:()=>({}),requestSubmit(){this.sent=(this.sent||0)+1;}};
const document={querySelector:s=>s==='[data-landing-service-search]'?field:form,addEventListener:(key,fn)=>events[key]=fn};
const window={};vm.runInNewContext(early,{window,document,location:{hash:'#/'},Event:class{}});
let prevented=0;events.submit({target:form,preventDefault(){prevented++;}});
assert.equal(prevented,1);
field.value='';window.QFEarly.restore({querySelector:()=>field});assert.equal(field.value,'Preciso montar guarda-roupa');
window.QFEarly.finish();assert.equal(form.sent,1);
field.value='Novo serviço';window.QFEarly.capture();field.value='';window.QFEarly.restore({querySelector:()=>field});assert.equal(field.value,'');
console.log('publicacao-leve: ordem de scripts, cache offline, conteúdo inicial e preservação de pedido antes do carregamento: ok');
// A primeira ativação da home mantém os nós já visíveis, sem trocar o candidato LCP.
const source=fs.readFileSync('index.html','utf8');
const render=source.slice(source.indexOf('  function renderAnon(found) {'),source.indexOf('  // V11.16.7 — atualização',source.indexOf('  function renderAnon(found) {')));
let rewrites=0,bound=0;
const content={style:{},set innerHTML(v){rewrites++;}};
const shell={setAttribute(){},getAttribute(){return 'home';},querySelector(){return {};},removeAttribute(){},set innerHTML(v){rewrites++;}};
const ctx={document:{getElementById:id=>id==='app-shell'?shell:content},global:{},Screens:{},window:{scrollTo(){}},routeKey:()=> 'inicio',bindGlobalDelegation(){bound++;}};
vm.createContext(ctx);vm.runInContext(render+'\nrenderAnon({route:{pattern:"/",render(){throw Error("Home já renderizada");}},params:{}});',ctx);
assert.equal(rewrites,0);assert.equal(bound,1);assert.ok(html.includes('data-qf-prerender="home"'));
