// UI isolada com respostas controladas. O SQL complementar testa o banco real com rollback.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const file=path.join(root,new URL(req.url,'http://local').pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}fs.readFile(file,(err,b)=>{if(err){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'text/html');res.end(b);});});
async function fixture(page){await page.evaluate(()=>{
 const id='a3333333-3333-4333-a333-333333333333';
 const f=window.qrFixture={plans:[{codigo:'essencial',nome:'Essencial',preco_centavos:19900,midia_centavos:10000,dias_campanha:7,vagas:1},{codigo:'destaque',nome:'Destaque',preco_centavos:39900,midia_centavos:20000,dias_campanha:14,vagas:3},{codigo:'premium',nome:'Premium',preco_centavos:69900,midia_centavos:40000,dias_campanha:21,vagas:5}],packs:[{id:'a4444444-4444-4444-a444-444444444444',codigo:'essencial',vagas:1,midia_centavos:10000,dias_campanha:7,preco_centavos:19900,valido_ate:new Date(Date.now()+86400000*30).toISOString()}],jobs:[{id,pacote_id:'a4444444-4444-4444-a444-444444444444',empresa:'Empresa Exemplo',cargo:'Auxiliar de produção',cidade:'Campinas',uf:'SP',descricao:'Atuação na linha de produção, organização e apoio à equipe.',requisitos:'Disponibilidade de horário.',beneficios:'Vale-transporte.',quantidade:2,salario:'R$ 2.000 a R$ 2.400',status:'aberta',campanha_status:'ativa',visitas:42,impressoes:2300,investimento_centavos:3500}],candidates:[{id:'a5555555-5555-4555-a555-555555555555',vaga_id:id,nome:'Mariana de teste',telefone:'11999999999',cidade:'Campinas',experiencia:'Experiência em atendimento e produção.',disponibilidade:'Imediata',status:'novo'}],saldo:0,paymentStatus:'pendente',calls:[],buyKeys:{}};
 const fake={auth:{getSession:async()=>({data:{session:null}})},from(table){let filters=[];const q={select(){return q;},order(){return q;},eq(k,v){filters.push(x=>x[k]===v);return q;},in(k,v){filters.push(x=>v.includes(x[k]));return q;},single(){return q.then(x=>({...x,data:x.data[0]}));},maybeSingle(){return q.single();},then(resolve,reject){let values=table==='qf_recrut_planos'?f.plans:table==='qf_recrut_pacotes'?f.packs:table==='qf_recrut_vagas'?f.jobs:table==='qf_recargas'?[{id:'pay-test',status:f.paymentStatus}]:f.candidates;return Promise.resolve({data:values.filter(x=>filters.every(fn=>fn(x))),error:null}).then(resolve,reject);}};return q;},async rpc(name,{p_acao:a,p_dados:p}){f.calls.push({a,p});let data={ok:true};if(a==='vaga_publica')data={ok:true,vaga:f.jobs.find(j=>j.id===p.id)};if(a==='comprar'){if(f.buyKeys[p.chave])data={ok:true,pacote:f.buyKeys[p.chave]};else if(f.saldo<19900)data={ok:false,reason:'saldo_insuficiente',faltam:19900-f.saldo};else{f.saldo-=19900;f.buyKeys[p.chave]=f.packs[0];data={ok:true,pacote:f.packs[0]};}}if(a==='salvar_vaga')data={ok:true,id:f.jobs[0].id};if(a==='status_candidato')f.candidates.find(c=>c.id===p.id).status=p.status;if(a==='status_vaga')f.jobs.find(j=>j.id===p.id).status=p.status;if(a==='admin_painel')data={ok:true,vagas:f.jobs.map(j=>({...j,candidatos:1,midia_pacote:10000,dias_campanha:7})),pacotes:f.packs};return {data,error:null};},storage:{from(){return {upload:async()=>({data:{},error:null})};}}};
 const cloud=window.QFCloud||window.QFAdminCloud;cloud.enabled=false;cloud.client=fake;cloud.createRecharge=async(amount,method)=>({id:'pay-test',valor:amount,metodo:method,pixCopyPaste:'codigo-pix-teste'});
 cloud.needsForcedPasswordChange=async()=>false;if(window.QFPush){window.QFPush.needsPermission=()=>false;window.QFPush.isActive=()=>true;window.QFPush.refreshStatus=async()=>true;window.QFPush.permission=()=> 'granted';}
 window.DB.resetDemoData();window.DB.setSession(window.QFCloud?{role:'profissional',userId:'pro_carlos'}:{role:'admin',userId:'admin_1'});
 });}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({executablePath:process.env.QR_CHROMIUM_PATH||undefined,headless:true,args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--single-process','--no-zygote']});
 try{const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**/*',r=>r.abort());await page.goto(url+'/index.html?demo=1');await page.waitForFunction(()=>!!window.QFRecrutamento);await fixture(page);
  await page.evaluate(()=>navigate('/profissional/home',true));await page.locator('[data-nav="/profissional/recrutamento"]').first().waitFor();await page.evaluate(()=>PU.closeSheet());await page.locator('[data-nav="/profissional/recrutamento"]').first().click();await page.getByRole('heading',{name:'Suas vagas'}).waitFor();
  assert.equal(await page.locator('.qr-plans .qr-card').count(),3);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'/tmp/qr-mobile-painel.png',fullPage:true});
  await page.getByRole('button',{name:'Cadastrar vaga',exact:true}).click();await page.getByLabel('Nome da empresa').fill('Empresa Teste');await page.getByLabel('Cargo',{exact:true}).fill('Auxiliar de produção');await page.getByLabel('Cidade',{exact:true}).fill('Campinas');await page.getByLabel('UF',{exact:true}).fill('SP');await page.getByLabel('Descrição da vaga').fill('Descrição completa de uma oportunidade de trabalho para teste.');await page.getByRole('button',{name:'Salvar vaga',exact:true}).click();await page.getByRole('heading',{name:'Candidatos · 1'}).waitFor();
  assert.equal(await page.getByRole('link',{name:'Chamar no WhatsApp'}).getAttribute('href'),'https://wa.me/5511999999999');await page.getByLabel('Etapa da seleção').selectOption('entrevista');await page.locator('.qr-badge--entrevista').waitFor();
  await page.evaluate(()=>navigate('/recrutamento/vaga/a3333333-3333-4333-a333-333333333333',true));await page.getByRole('heading',{name:'Quero me candidatar'}).waitFor();assert.equal(await page.evaluate(()=>DB.getSession().role),'profissional');await page.screenshot({path:'/tmp/qr-mobile-vaga.png',fullPage:true});
  await page.getByLabel('Seu nome',{exact:true}).fill('João de teste');await page.getByLabel('WhatsApp com DDD').fill('11 99999-9888');await page.getByLabel('Sua cidade').fill('Campinas');await page.locator('[name="consentimento"]').check();await page.getByRole('button',{name:'Enviar candidatura grátis'}).click();await page.getByRole('heading',{name:'Candidatura recebida!'}).waitFor();
  assert.equal(await page.evaluate(()=>qrFixture.calls.filter(c=>c.a==='candidatar').length),1);
  await page.evaluate(()=>navigate('/profissional/recrutamento',true));await page.getByRole('button',{name:'Contratar Essencial',exact:true}).click();await page.getByRole('button',{name:'Confirmar contratação',exact:true}).click();await page.getByRole('button',{name:'Gerar pagamento',exact:true}).click();await page.getByRole('button',{name:'Já paguei · ativar pacote',exact:true}).click();assert.equal(await page.evaluate(()=>Object.keys(qrFixture.buyKeys).length),0);
  await page.evaluate(()=>{qrFixture.paymentStatus='aprovado';qrFixture.saldo=19900;});await page.getByRole('button',{name:'Já paguei · ativar pacote',exact:true}).click();await page.getByRole('heading',{name:'Suas vagas'}).waitFor();assert.equal(await page.evaluate(()=>qrFixture.saldo),0);assert.equal(await page.evaluate(()=>Object.keys(qrFixture.buyKeys).length),1);
  await page.setViewportSize({width:1440,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'/tmp/qr-desktop-painel.png',fullPage:true});
  await page.goto(url+'/admin.html');await page.waitForFunction(()=>!!window.QFRecrutamento);await fixture(page);await page.evaluate(()=>navigate('/admin/dashboard',true));await page.locator('[data-nav="/admin/recrutamento"]').first().click();await page.getByText('Pacotes vendidos',{exact:false}).waitFor();await page.locator('summary').click();await page.getByLabel('Status da campanha').selectOption('em_preparacao');await page.getByRole('button',{name:'Salvar acompanhamento'}).click();
  assert.deepEqual(errors,[]);console.log('PASS: navegação preservada; painel mobile/desktop sem overflow; cadastro da vaga; contatos e etapas; candidatura sem login; Pix pendente não ativa, confirmado debita uma vez; admin sem erros JS.');
 }finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
